### ISSUE TITLE
Maintain full screen after loading the next video page

### ISSUE THREAD

**Issue by ptrm** [darajava/youtube-smooth#31]
It would be great if after the next video is loaded the full screen mode was switched back on again if it had been turned on before. Even greater, if it was maintained seamlessly the way YouTube's autoplay feature works;)

**Comment by darajava** [comment]
I'm afraid I don't think this is possible. I'm gonna close it for now :(

**Comment by darajava** [comment]
Maybe this is possible

**Comment by darajava** [comment]
Nope, not possible I'm afraid: http://stackoverflow.com/questions/37953277/inject-javascript-into-youtube-to-make-video-fullscreen/37953398#37953398
